name = "BlockDiagonalMatrices"
uuid = "0667cdb8-769f-46fc-811d-3dbddc30cb80"
authors = ["Mikkel Paltorp"]
version = "1.0.0-DEV"

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
FLoops = "cc61a311-1640-44b5-9fba-1b764f453329"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Aqua = "0.8"
ArrayInterface = "7.18.0"
FLoops = "0.2"
LinearAlgebra = "1"
SafeTestsets = "0.1"
SparseArrays = "1"
StaticArrays = "1.9"
Test = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "StaticArrays", "SafeTestsets"]
